import { Contact } from 'src/app/create-contact/shared/contact.model';
import { v4 as uuidv4 } from 'uuid';
export const CONTACTLIST: Contact[] = [
  {
    id: uuidv4(),
    nome: 'ARLINDO BONINA',
    cpf: '01529871263',
    logradouro: 'Rua Desembargador Arno Hoeschl',
    bairro: 'Centro',
    cep: '88015620',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'CHARLESTON',
    cpf: '90950445991',
    logradouro: 'Rua Madalena Barbi',
    bairro: 'Centro',

    cep: '88015190',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Guilherme Pfeifer',
    cpf: '06655899990',
    logradouro: 'Rua Francisco Tolentino',
    bairro: 'Centro',
    cep: '88010200',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'JOYCE guimarães',
    cpf: '04700405996',
    logradouro: 'Rua Madalena Barbi',
    bairro: 'Centro',
    cep: '88015190',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Rodrigo Fernandes da Silva',
    cpf: '04122165903',
    logradouro: 'Rua João Meirelles',
    bairro: 'Abraão',
    cep: '88085201',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Bruno Vasconcelos',
    cpf: '01529871263',
    logradouro: 'Rua Desembargador Arno Hoeschl',
    bairro: 'Centro',
    cep: '88015620',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Fernanda Vasconcelos',
    cpf: '90950445991',
    logradouro: 'Rua Madalena Barbi',
    bairro: 'Centro',

    cep: '88015190',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Lua Fagundes',
    cpf: '06655899990',
    logradouro: 'Rua Francisco Tolentino',
    bairro: 'Centro',
    cep: '88010200',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Victoria Helena Barbosa',
    cpf: '04700405996',
    logradouro: 'Rua Madalena Barbi',
    bairro: 'Centro',
    cep: '88015190',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
  {
    id: uuidv4(),
    nome: 'Henrique Domingues',
    cpf: '04122165903',
    logradouro: 'Rua João Meirelles',
    bairro: 'Abraão',
    cep: '88085201',
    localidade: 'Florianópolis',
    uf: 'SC',
  },
];
